apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-telemetry
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  destination:
    namespace: kubeflow
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
  project: default
  source:
    path: charts/common/aws-telemetry
    repoURL: https://github.com/awslabs/kubeflow-manifests/
    targetRevision: release-v1.7.0-aws-b1.0.1
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true