apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-telemetry
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  destination:
    namespace: kubeflow
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/common/aws-telemetry
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5