apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-issuer
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  destination:
    namespace: kubeflow
    name: {{ .Values.spec.destination.name }}
  project: default
  source:
    path: charts/common/kubeflow-issuer
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
