apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-local-gateway
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/common/cluster-local-gateway
    repoURL: https://github.com/awslabs/kubeflow-manifests/
    targetRevision: release-v1.7.0-aws-b1.0.1
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true