apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: profiles-and-kfam
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kubeflow
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/apps/profiles-and-kfam
    repoURL: https://github.com/awslabs/kubeflow-manifests/
    targetRevision: release-v1.7.0-aws-b1.0.1
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m