apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: kubeflow-gitops
  region: us-east-1
  version: "1.25"
  tags:
    karpenter.sh/discovery: kubeflow-gitops

iam:
  withOIDC: true

addons:
- name: vpc-cni
- name: aws-ebs-csi-driver
- name: coredns

managedNodeGroups:
- instanceType: m5.xlarge
  amiFamily: AmazonLinux2
  name: kubeflow-gitops-ng
  desiredCapacity: 5
  minSize: 5
  maxSize: 10