apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: kserve-gitops
  region: us-east-1
  version: "1.25"
  tags:
    karpenter.sh/discovery: kserve-gitops

iam:
  withOIDC: true

addons:
- name: vpc-cni # no version is specified so it deploys the default version
  attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
- name: coredns
  version: latest # auto discovers the latest available
- name: kube-proxy
  version: latest
- name: aws-ebs-csi-driver
  wellKnownPolicies:      # add IAM and service account
    ebsCSIController: true

managedNodeGroups:
- instanceType: m5.xlarge
  amiFamily: AmazonLinux2
  name: kserve-gitops-ng
  desiredCapacity: 5
  minSize: 5
  maxSize: 10