apiVersion: v2
name: kubeflow-on-aws
description: Applications
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: cert-manager
    version: v1.10.1
    repository: https://charts.jetstack.io